import { Roboto_Slab } from "next/font/google";
import Providers from "@/Components/Providers";
import Header from "@/Components/Header";

const roboto = Roboto_Slab({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <Providers>
            <html lang="en">
                <body className={roboto.className}>
                    <Header />
                    {children}
                </body>
            </html>
        </Providers>
    );
}
